Upgrade dependencies
dusk-network/rusk pull request #1358
Opened 2024-02-08 13:09 UTC by kieranhall

Resolves #1284

2024-02-08 15:45 UTC, ascartabelli requested changes
I'd like to remove the added `await` in the layout load.

I would also add an entry in the changelog, maybe specifying the major change (SvelteKit) other than the generic dependency update.

Not sure it's ideal to merge it now, anyway, as discussed.

2024-02-08 15:45 UTC, ascartabelli commented on web-wallet/src/routes/(app)/dashboard/+layout.js
> +		currentPrice: await fetch("https://api.dusk.network/v1/quote")
That's why you had the error in the tests: I didn't want to await to avoid blocking the UI while the call resolves.

2024-02-08 15:45 UTC, ascartabelli commented on web-wallet/src/lib/dusk/components/Toast/store.js
> + * @param {ReturnType<typeof setTimeout>} timeout
This can be just `number` as it is in the browser. 
We need to call `setTimeout` & co. with `window.setTimeout` though to make TS understand.

2024-02-08 15:45 UTC, ascartabelli commented on web-wallet/src/routes/(app)/dashboard/__tests__/layout.spec.js
> +			expect(result.currentPrice).toStrictEqual(currentPrice.market_data.current_price);
See above about awaiting

2024-02-08 15:45 UTC, ascartabelli commented on web-wallet/src/routes/(app)/dashboard/__tests__/layout.spec.js
> +			expect(result1.currentPrice).toStrictEqual({});
See above about awaiting

2024-02-08 15:45 UTC, ascartabelli commented on web-wallet/src/routes/(app)/dashboard/__tests__/layout.spec.js
> +			expect(result1.currentPrice).toStrictEqual({});
See above about awaiting

2024-02-09 10:41 UTC, kieranhall commented
This branch has more issues than first seen.  I'm going to close this PR until further investigation reveals the source of the problem.

![image](https://github.com/dusk-network/rusk/assets/1401918/9b32077b-a81e-4de6-912d-dcf43cc6e223)

2024-02-09 10:41 UTC, closed without merging