Update transfer events
dusk-network/rusk pull request #2500
Opened 2024-09-27 18:16 UTC by Neotamandua

Changes:
- Use consts for event topics in transfer contract events so that we can also use that const imported elsewhere to match on topics.
- Rename "from" & "to" into "sender" & "receiver" for MoonlightTransactionEvent and related logic, so that it is consistently called sender/receiver in every context.
- Standardize field order to sender, receiver, value in all transfer event structs
- Changed "CONVERT" to "convert" as it is lower case in the other cases

2024-09-27 18:50 UTC, moCello approved these changes
Generally looks good! But maybe it's an idea to rename `Transaction::sender` to `phoenix_sender` to match the new `moonlight_sender` and avoid confusion

2024-09-30 08:59 UTC, Neotamandua commented
> maybe it's an idea to rename `Transaction::sender` to `phoenix_sender` to match the new `moonlight_sender`

Good idea, I made the relevant change

2024-09-30 09:49 UTC, HDauven approved these changes

2024-09-30 10:06 UTC, moCello requested changes
Thanks for adding the changes and there is one more thing (sorry I didn't catch that earlier) but in the rusk repo we need to split every commit so that it is clearly mentioned which workspace member is affected by the changes. E.g. your first commit needs to be split into 5 (one for each `execution-core`, `node-data`, `rusk-wallet`, `test-wallet` and `rusk`).

2024-09-30 11:42 UTC, moCello commented on rusk-wallet/src/wallet.rs
>          from_addr: &Address,
the `from_addr` should also become `sender_addr`

2024-10-01 10:25 UTC, moCello commented on rusk-wallet/src/wallet.rs
> +        let sender = self.bls_public_key(from_index);
`from_index` becomes `sender_index`

2024-10-01 10:26 UTC, moCello commented on test-wallet/src/imp.rs
>          from_index: u8,
here too, and possibly in other places as well

2024-10-01 12:10 UTC, moCello approved these changes
Very nice changes!

2024-10-01 12:31 UTC, merged