Add Moonlight history
dusk-network/rusk pull request #2521
Opened 2024-09-29 18:37 UTC by Neotamandua

2024-09-30 19:54 UTC, Neotamandua commented
The PR is ready for review, but still needs an additional commit based on the changes from https://github.com/dusk-network/rusk/pull/2500, which include const for event topics so that events are matched on const instead of raw written &str's

2024-10-02 10:32 UTC, miloszm requested changes
In general looks good, but minor improvements would be nice to have.

2024-10-02 10:32 UTC, miloszm commented on node/src/archive/transformer.rs
> +            continue;
Why is the "continue" needed here? If else part is removed, the meaning is the same unless I miss sth.

2024-10-02 10:32 UTC, miloszm commented on node/src/archive/transformer.rs
> +                    false
I find the mix of 'return' and direct values confusing. Could this be unified? For example returns eliminated?

2024-10-02 10:32 UTC, miloszm commented on node/src/archive.rs
> +    fn fetch_moonlight_historys(
nitpick but shouldn't it be 'histories' ?

2024-10-02 10:32 UTC, miloszm commented on node/src/archive.rs
> +    async fn remove_deleted_block(
Nitpick - could it be just 'remove_block'? It sounds really redundant, also mixes a command with a reason for the command, which mixes up two concerns.

2024-10-02 11:12 UTC, miloszm approved these changes
LGTM

2024-10-02 11:50 UTC, merged