rusk-wallet: Add stdout_format flag to binary
dusk-network/rusk pull request #2700
Opened 2024-10-18 04:00 UTC by Daksh14

Closes #2664 

- Add stdout_format flag to binary
- Add `to_json` for `RunResult`
- Remove duplicate code in main.rs

2024-10-20 19:43 UTC, HDauven commented
What about situations where the wallet file is missing? Should the error be JSON wrapped to also be parsable? 

What if there's no stake for a given key? Should it return that as an error or just have all values default to zero? Since having no stake or rewards is equivalent to not having a key that stakes.

2024-10-20 20:45 UTC, Daksh14 commented
@HDauven I added a `has_stake` field in the json output. If the wallet file is missing then the wallet will not initialize no json will be emitted just an error

2024-10-21 07:33 UTC, herr-seppia requested changes
We should inform the user about the invalid eligibility

2024-10-21 07:33 UTC, herr-seppia commented on rusk-wallet/src/bin/command.rs
> +                        "eligibility": eligibility,
What if the user has less stake than the minimum amount due to a Slash?

2024-10-25 14:06 UTC, herr-seppia commented on rusk-wallet/src/bin/command.rs
> +                None => serde_json::Value::Null,
this is not true, user can have rewards without a valid active stake 

to be more precise, data.amount can be none, but you can still have other info to show
```json

    {
        "amount": 0,
        "eligibility": 0,
        "faults": 0,
        "hard_faults": 0,
        "key": "mvft6AXjR1mDtg1Qo3GzGBKZAvvxY1S6h41DSEPh9Ewj9GFR61rPQnjVaM1W9nqkHijRC2d5Yo4FSBwU8wf9eHeEJYXuMSrB7eJxvsY6HjCeDJ9pKfJLdjayAfrxEyudvx2",
        "locked_amt": 0,
        "reward": 23261220305196
    },
```

2024-10-25 14:37 UTC, herr-seppia commented on rusk-wallet/src/bin/command.rs
> +                None => serde_json::Value::Null,
Addressed by https://github.com/dusk-network/rusk/pull/2774

2024-11-21 07:25 UTC, herr-seppia requested changes

2024-11-21 07:25 UTC, herr-seppia commented on rusk-wallet/src/bin/command.rs
> -                    writeln!(f, "> No active stake found for this key")?;
Why this has been removed?

2024-11-21 07:25 UTC, herr-seppia commented on rusk-wallet/src/bin/main.rs
> +                stdout_res = run_res.to_json();
Can you put an if else and avoid to "run_res.to_string()"?

2024-11-21 07:25 UTC, herr-seppia commented on rusk-wallet/src/bin/command.rs
> +    pub fn to_json(&self) -> String {
Why don't you implement serde::Serialize for RunResult?

2025-02-15 19:35 UTC, Daksh14 commented
Long living branch

2025-02-15 19:35 UTC, closed without merging