rusk-wallet: Add early check for state and prover endpoint status
dusk-network/rusk pull request #2701
Opened 2024-10-18 04:38 UTC by Daksh14

- Fix clashing of newly added command flag `profile_idx` w… …ith `gas_price`
- Add a check for status of state and prover and exit early if its not success

2024-10-18 05:28 UTC, herr-seppia requested changes

2024-10-18 05:28 UTC, herr-seppia commented on rusk-wallet/src/bin/command.rs
> +        #[clap(short = 'a', long)]
Be consistent (this is "a", the others are "s")


Btw, I would remove the short version and use only the long

2024-10-18 05:32 UTC, herr-seppia requested changes

2024-10-18 05:32 UTC, herr-seppia commented on rusk-wallet/src/bin/main.rs
> +
We cannot exit if there is no connection!

User should still be able to do some operation, that's why there was a different menu for when the client were offline (now that menu is displayed when wallet is not synced, idk why)

2024-10-22 08:35 UTC, moCello commented
superseded by #2719

2024-10-22 08:35 UTC, closed without merging