transfer-circuits: Split ExecuteCircuit into separated instances
dusk-network/rusk pull request #300
Opened 2021-05-17 15:04 UTC by vlopes11

Currently the transfer circuit is a single struct implementation that
will iterate its attributes to produce different circuits.

This doesn't work with the new circuit hasher structure because it uses
the gadget code to generate the identifier of a circuit.

The current implementation will produce different circuits with the same
gadget code depending on the inputs.

This commit splits the `ExecuteCircuit` into different concrete
structures and uses an enum mapping to encapsulate the inputs and
outputs operations.

Resolves #275

2021-05-17 16:04 UTC, CPerezz requested changes
A couple of changes requested for sure.
- `code-hasher` has to stablish the `CIRCUIT_ID` and any other id method should be removed.
- The way to obtain the keys, should be reworked and adapted to how it is being done in rusk-profile.
- There is a conflict in the PR, it should be solved.

As for the structure in general of not using const_generics. I think it would reduce the code enabling the possibility of making generic functions. I could be wrong, so @ZER0 's input would be appreciated.

2021-05-17 16:04 UTC, CPerezz commented on circuits/transfer/src/lib.rs
> +//#![feature(const_evaluatable_checked)]
I guess this is a leftover

2021-05-17 17:44 UTC, vlopes11 commented on circuits/transfer/src/execute.rs
> +            Self::ExecuteCircuitFourTwo(_) => "transfer-execute-4-2",
I believe this function will be removed in the same PR we introduce the code hasher, yes?

2021-05-17 17:44 UTC, vlopes11 commented on circuits/transfer/src/execute.rs
> +                println!("C {:?}", self);
Oh, shouldn't have a println there. But Shouldnt panic either, there is a specific error when the user attempt to insert more than 4 inputs

2021-05-17 17:45 UTC, vlopes11 commented on circuits/transfer/src/execute/variants.rs
> +            pub fn public_inputs(&self) -> Vec<PublicInputValue> {
Yes, I was about to make that suggestion.

2021-05-18 08:26 UTC, vlopes11 commented on circuits/transfer/src/execute.rs
> +                println!("C {:?}", self);
Fixed

2021-05-18 08:26 UTC, vlopes11 commented on circuits/transfer/src/execute.rs
> +            Self::ExecuteCircuitFourTwo(_) => "transfer-execute-4-2",
As agreed, the code-hasher PR will be a follow up

2021-05-18 08:26 UTC, vlopes11 commented on circuits/transfer/src/execute/variants.rs
> +            const CIRCUIT_ID: [u8; 32] = [0xff; 32];
As agreed, the code-hasher PR will be a follow up

2021-05-18 08:27 UTC, vlopes11 commented on circuits/transfer/src/keys.rs
> +{
As agreed, the code-hasher PR will be a follow up

2021-05-18 20:31 UTC, vlopes11 commented on circuits/transfer/src/lib.rs
> +//#![feature(const_evaluatable_checked)]
Fixed

2021-05-18 20:31 UTC, vlopes11 commented on circuits/transfer/src/keys.rs
> +        Ok((pp, pk, vd))
Fixed

2021-05-18 20:32 UTC, vlopes11 commented on circuits/transfer/src/execute.rs
> +    ) -> Result<(PublicParameters, ProverKey, VerifierData), Error>
The purpose of this function changed with the introduction of the code hasher.

Now it will take a generic impl of Circuit and return the keys

2021-05-19 13:24 UTC, CPerezz approved these changes
A few nits.

For the rest, LGTM once addressed!

2021-05-19 18:29 UTC, ZER0 approved these changes
LGTM with @CPerezz comments addressed.

In particular, move outside the library `keys.rs` since it looks like it belongs to the tests. 

There are also another couple of things that we could simplify but we can wait once we make the `Circuit` trait object safe.

2021-05-20 09:55 UTC, vlopes11 commented on circuits/transfer/src/keys.rs
> +}
Agreed. Fixed, moved to tests module.

2021-05-20 09:55 UTC, vlopes11 commented on circuits/transfer/src/execute/builder.rs
>          let label = b"dusk-network";
Agreed. Fixed

2021-05-20 09:55 UTC, vlopes11 commented on circuits/transfer/Cargo.toml
> +code-hasher = { version = "0.1", path = "../../macros/code-hasher" }
Agreed. Fixed

2021-05-20 09:55 UTC, vlopes11 commented on circuits/transfer/Cargo.toml
> +phoenix-core = { git = "https://github.com/dusk-network/phoenix-core", tag = "v0.11.0-rc.0", features = ["canon"] }
Fixed

2021-05-20 09:56 UTC, merged