execution-core: truncate trace logs of contract deployments
dusk-network/rusk pull request #3025
Opened 2024-11-19 16:15 UTC by d-sonuga

To resolve the noisy log as described in #2742, the `ContractDeploy::bytecode` field now pretty prints as `ContractBytecode { ... }` and the Phoenix transaction's `proof` field now pretty prints as `[ ... ]`.

2024-11-20 10:00 UTC, moCello commented
I understand that the contract byte-code and the transaction proof can pollute the output of the node-log.
Modifying the `Debug` trait for remedy isn't the right approach though as the Debug trait is meant for debugging purposes and printing the bytecode and proof can be beneficial in some circumstances.

Since this is an issue with the `node` log, it might make sense to also fix it in the `node` log and not on `execution-core` level where every change affects the entire network.

2024-11-20 14:05 UTC, d-sonuga commented
`Message` defined [here](https://github.com/dusk-network/rusk/blob/8104f7c46822c627fcea7508314e88323e1c155e/node-data/src/message.rs#L99) and `Payload` defined [here](https://github.com/dusk-network/rusk/blob/8104f7c46822c627fcea7508314e88323e1c155e/node-data/src/message.rs#L412) are the structs that get logged in `node` and `node-data` which may contain `ContractBytecode`.

I've changed the log messages to avoid outputting the entire structs.

2024-11-20 14:07 UTC, herr-seppia requested changes
I though that the originally issue were already solved by some @fed-franz PR

What are the logs that we're trying to truncate here? 
I understood that they are related to the contract deployment, but I don't get which they are and how this PR would truncate them

2024-11-20 14:19 UTC, herr-seppia commented
There is no trace of ContractDeployment in your changes.

The issue was created when the code was dumping the whole block (including transactions and optionally their contract deployment), but this has been changed by fed's pr 

Hence my question. 
Are you able to replicate the log that you want to truncate?

2024-11-20 14:22 UTC, d-sonuga commented on node-data/src/message.rs
> +    }
I can't seem to find a `topic` function defined for `node_data::message::Payload`.

2024-11-20 14:48 UTC, herr-seppia commented
> @herr-seppia, yes I can replicate it. 

Perfect, can you post on the original issue how to?
Anyway, I'm against in shading the whole messages as you're proposing, but I would like to have a more punctual fix

2024-11-20 15:31 UTC, d-sonuga commented
@herr-seppia, the replication is [here](https://github.com/dusk-network/rusk/issues/2742#issuecomment-2488881967).
And perhaps in addition to the new reduced warn/error logs in this PR, trace logs could be added to output more information?

2024-11-20 16:15 UTC, herr-seppia commented
> @herr-seppia, the replication is [here](https://github.com/dusk-network/rusk/issues/2742#issuecomment-2488881967). And perhaps in addition to the new reduced warn/error logs in this PR, trace logs could be added to output more information?

The branch you proposed is actually throwing an error on purpose everytime a transaction is broadcasted.
My request was to use an official rusk node and try to reproduce the log pollution.

ps: Having the whole message dumped if an encoding error happens LGTM, because it's a bug that needs investigation

2024-11-20 16:34 UTC, d-sonuga commented
Okay, since that's the case, I guess the issue should be considered resolved already?

2025-03-28 12:49 UTC, Neotamandua commented
Closing as obsolete

2025-03-28 12:49 UTC, closed without merging