rusk-wallet: Implement moonlight history
dusk-network/rusk pull request #3284
Opened 2024-12-22 21:39 UTC by Daksh14

2024-12-23 08:32 UTC, herr-seppia requested changes
Would be possible to have a tx history containing both Phoenix and moonlight transactions?
Why did you split them?

Additionally (but not blockers):
- try to store the history in rocksdb to improve performance and unload archival computation (we already store Notes, you only miss the derived TransactionHistory objects)
- add a warning if the user is not connected to an archival

2024-12-23 08:52 UTC, Daksh14 commented
> Would be possible to have a tx history containing both Phoenix and moonlight transactions?
> Why did you split them?
> 
> Additionally (but not blockers):
> - try to store the history in rocksdb to improve performance and unload archival computation (we already store Notes, you only miss the derived TransactionHistory objects)
> - add a warning if the user is not connected to an archival

Mixing the moonlight and phoenix tx history would be confusing no? I can add another column that displays transaction type but that would add more info and make it harder to read

I split the history because all other methods are also split on public/private it makes sense.

Can you create issue for those two points you mentioned?

2024-12-23 10:08 UTC, Neotamandua commented
> Mixing the moonlight and phoenix tx history would be confusing no? I can add another column that displays transaction type but that would add more info and make it harder to read

In the long run, I think it is necessary to add such a column anyway. Because we want to differentiate between different types of transactions (transfer out, transfer in, conversion, deposit, withdrawal, etc.).

2024-12-23 16:47 UTC, herr-seppia commented
> Because we want to differentiate between different types of transactions (transfer out, transfer in, conversion, deposit, withdrawal, etc.).

These infos are already available in the transaction history in the "method" column IIRC

2024-12-28 20:04 UTC, Daksh14 commented
@herr-seppia lets keep the moonlight and phoenix history seperate for now, we dont have to sync if we're just fetching moonlight history

2024-12-30 10:40 UTC, Neotamandua commented on rusk-wallet/src/bin/command.rs
> +                    tracing::error!("Cannot fetch archival history");
```suggestion
                    tracing::error!("Cannot fetch archive history");
```

2024-12-30 10:40 UTC, Neotamandua commented on rusk-wallet/src/bin/command.rs
> +                let public_key = wallet.public_address(profile_idx)?;
```suggestion
                let address = wallet.public_address(profile_idx)?;
```

2024-12-30 10:40 UTC, Neotamandua commented on rusk-wallet/src/error.rs
> +    ArchivalJsonError(String),
```suggestion
    #[error("Archive node query error: {0}")]
    ArchiveJsonError(String),
```

2025-01-01 13:54 UTC, Neotamandua approved these changes

2025-01-13 18:04 UTC, merged