stake-contract: Add docs comments
dusk-network/rusk pull request #3304
Opened 2024-12-30 16:24 UTC by moCello

Resolves #3303

2025-06-10 10:23 UTC, fed-franz requested changes

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/lib.rs
> +//! [Dusk Whitepaper](https://dusk-cms.ams3.digitaloceanspaces.com/Dusk_Whitepaper_2024_4db72f92a1.pdf)
Not sure I would link the whitepaper to be honest... it's not that it's much more detailed than the docs and having a link to digitaloceanspaces feels a bit awkward to be.

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +/// Tracks active stakes, burnt amounts, and configurations.
There is actually only one stake per provisioner. 
I guess this structure is obsolete and we don't update it because it would be a breaking change. But maybe we could add a note somewhere. 
@herr-seppia can you confirm this?

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +/// public key. This stake has a maturation period of minimal one [`EPOCH`],
To be precise, the maturation period corresponds to the number of blocks until the end of the epoch in which the stake occurred, plus an entire extra epoch.  
Put simply, if a stake is created in epoch X, it becomes eligible at the beginning of the epoch X+2.

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +/// - `burnt_amount`: Total amount of tokens burnt due to penalties or other
I would avoid using `token` here, given it meaning at the application layer

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +    /// Configures the [`StakeState`] with a new staking configuration.
```suggestion
    /// Updates the configuration of a [`StakeState`].
```

just a suggestion

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +    /// This method should be called at the end of each block.
This is actually called at the beginning of the creation of a new block (hence the name). 
I agree that it would make sense to call it at the end of each block, but I guess there's some technical reason for which it can't be done.

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +    /// A first time stake needs to mature for at least on [`EPOCH`] before it
Check the previous comment on maturity

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +    /// If there is a mature stake in the state for the provided [`StakeKeys`],
Again, there is only one stake. In this case, `stake` simply updates the amount. I think the comment should say sth like this: if the stake is already eligible, its amount is updated but 1/10 of the topup will be locked.

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +    /// Processes staking from a smart contract.
I'd rather use the verb "to stake" directly: Stakes an amount for a given smart contract

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +    /// Initiates an unstake request for a given account.
Why initiates? Unstakes have immediate effect

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +    /// Processes an unstake request originating from a smart contract.
Like before, I'd avoid using "process" as the main verb.

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +    ///
Maybe we can add a note clarifying that this function is only used when recoverying the state or for testing purposes, while the actual creation of a new stake is done by the `stake` method.
I think this would avoid confusion, because `insert_stake` might give the wrong idea this is called when actually creating a new stake

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
>      /// If said stake doesn't exist, a default one is inserted and a mutable
Bit weird to start with this sentence. Can we add a one-liner descriptor like for other methods?

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +    /// - `rewards`: A vector of reward details.
```suggestion
    /// - `rewards`: A vector with the rewards to assign.
```

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +    /// Penalizes a given account by slashing a specified amount.
Locks a given amount from a stake as a penalization.
This is also known as "soft" slash

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +    /// Performs a severe penalty by slashing a specified amount of stake from
Burns the specified amount from a given slash as penalty for a hard fault

2025-06-10 10:23 UTC, fed-franz commented on contracts/stake/src/state.rs
> +    /// Sets the total amount of burnt tokens within the staking state. Burnt
As before, I'd rather not use `token` in this context. I'd say coins, or simply DUSK

2025-06-10 10:35 UTC, moCello commented on contracts/stake/src/lib.rs
> +//! [Dusk Whitepaper](https://dusk-cms.ams3.digitaloceanspaces.com/Dusk_Whitepaper_2024_4db72f92a1.pdf)
Is there a more suitable link to the docs?

2025-06-11 08:17 UTC, fed-franz commented on contracts/stake/src/lib.rs
> +//! [Dusk Whitepaper](https://dusk-cms.ams3.digitaloceanspaces.com/Dusk_Whitepaper_2024_4db72f92a1.pdf)
I would simply leave the one below (docs.dusk.network). But you can also add a link to https://github.com/dusk-network/dusk-protocol

2026-08-31 12:17 UTC, closed without merging