rusk: Add gRPC service for Network communication
dusk-network/rusk pull request #383
Opened 2021-12-02 15:43 UTC by herr-seppia

Resolves #380

2021-12-13 17:36 UTC, vlopes11 reviewed
Couple if nits

2021-12-13 17:36 UTC, vlopes11 commented on rusk/src/bin/main.rs
> +    let app = self::network_config(app);
`self` is a bit confusing here.

```suggestion
    let app = network_config(app);
```

2021-12-13 17:36 UTC, vlopes11 commented on rusk/src/bin/main.rs
> +            .help("Public address you want to be identified with. Eg: 193.xxx.xxx.198:9999")
Can we put in the description the difference between the public address and the listen address?

2021-12-13 17:36 UTC, vlopes11 commented on rusk/src/lib/services/network.rs
> +        let grpc_sender = broadcast::channel(100).0;
We create a channel, but discard the receiver. Can we put a comment here on why that isn't a problem?

2021-12-13 17:36 UTC, vlopes11 commented on rusk/src/lib/services/network.rs
> +        info!("Recieved SendMessage request");
This looks like `trace` instead of `info`

2021-12-15 12:46 UTC, vlopes11 requested changes
LGTM overall, but need to check the problem with dusk analyzer (CI job) and rebase to current `testnet`

2021-12-16 10:56 UTC, herr-seppia commented
> LGTM overall, but need to check the problem with dusk analyzer (CI job) and rebase to current `testnet`

Anything should be OK now

2021-12-16 11:20 UTC, vlopes11 approved these changes
LGTM

2021-12-16 12:32 UTC, merged