Wallet CLI
dusk-network/rusk pull request #454
Opened 2022-01-21 17:37 UTC by t00ts

A reliable, user-friendly command-line interface for the Dusk wallet

Closes #391

2022-01-26 10:50 UTC, t00ts commented on rusk-wallet/src/main.rs
> +    let cmd = cfg.command.unwrap_or_else(|| CliCommand::None);
Use `unwrap_or` instead

2022-01-26 10:50 UTC, t00ts commented on rusk-wallet/src/main.rs
> +            Create => create(),
Need to pass arguments to `create()`, at least all path-related stuff in case user overrides

2022-01-26 10:50 UTC, t00ts commented on rusk-wallet/src/main.rs
> +    let prover_client = ProverClient::connect(rusk_addr.clone()).await?;
Can avoid `.clone()` on this last one

2022-01-26 10:50 UTC, t00ts commented on rusk-wallet/src/main.rs
> +
Remove extra newline

2022-01-26 10:50 UTC, t00ts commented on rusk-wallet/src/main.rs
> +    println!("Create a wallet!");
Remove print

2022-01-26 16:35 UTC, ureeves requested changes
Looks good overall, have some small changes here and there.

2022-01-26 16:35 UTC, ureeves commented on Cargo.toml
> +    "test-utils/transfer-wrapper"
What happened with this `,`? Some formatter?

2022-01-26 16:35 UTC, ureeves commented on rusk-wallet/Cargo.toml
> +whoami = "1.2.1"
Try not specifying the minor versions. Like this we get improvements for free.

2022-01-26 16:35 UTC, ureeves commented on rusk-wallet/Makefile
> +.PHONY: build test help
New line missing

2022-01-26 16:35 UTC, ureeves commented on rusk-wallet/src/lib/clients.rs
> +        // todo: encode message
I got some whiffs of this, but didn't really understand. Could the problem be clarified?

2022-01-26 16:35 UTC, ureeves commented on rusk-wallet/src/lib/clients.rs
> +        buf.put_slice(&signature.to_bytes());
Could you use the [`dusk_bytes::Write`](https://docs.rs/dusk-bytes/0.1.5/dusk_bytes/trait.Write.html) API?

2022-01-26 16:35 UTC, ureeves commented on rusk-wallet/src/lib/clients.rs
> +impl dusk_wallet_core::StateClient for State {
Is there a reason you're not importing this, and using the fully qualified path?

2022-01-26 22:53 UTC, xevisalle requested changes
Functions `from_file() `and `save()` in `store.rs` should be checked for consistency with the last changes done in a2b61d9c1599bf294d9fff69d7110e57e44f697b.

2022-01-27 08:45 UTC, herr-seppia commented on rusk-wallet/src/lib/clients.rs
> +        // todo: encode message
@t00ts @ureeves 
The tx propagated is intended to be handled by the node
The node is expecting a transaction wrapped into his IPC wire format [this way](https://github.com/dusk-network/dusk-blockchain/blob/0ec1a60f8e35f395581d528fc9a16410222eaa11/pkg/core/data/ipc/transactions/transaction.go#L23-L50)
Inside this wrapped format we find the [Phoenix tx](https://github.com/dusk-network/dusk-blockchain/blob/0ec1a60f8e35f395581d528fc9a16410222eaa11/pkg/core/data/ipc/transactions/payload.go#L16-L24) payload

There are 3 issue here:
1) Rusk should wrap the tx into the node IPC format
2) The [rusk Phoenix tx](https://github.com/dusk-network/wallet-core/blob/b5eaef22811ba074095087240e4a85d95de1ddae/src/tx.rs#L102-L140) is different
3) Clarify who should do this serialization. Imo not the wallet, it should be handled by the "Propagate" method. This means that we can "only" propagate transaction (idk if we need other type to be propagated atm)

2022-01-27 09:28 UTC, autholykos commented on rusk-wallet/src/lib/clients.rs
> +        // todo: encode message
Some fields need to be read by the golang process in order to populate fields in the block explorer. This is tackled in #450

2022-01-27 16:52 UTC, xevisalle approved these changes

2022-01-27 18:54 UTC, herr-seppia commented on rusk-wallet/src/lib/clients.rs
> +        // todo: encode message
Resolving this comment in #489

2022-01-30 18:54 UTC, ureeves requested changes

2022-01-30 18:54 UTC, ureeves commented on rusk-wallet/Cargo.toml
> +dusk-wallet-core = "0.8.0-rc.1"
This should be `0.8.0-rc`. In the meantime I'll yank `rc.1` to prevent its usage.

2022-01-30 18:56 UTC, ureeves requested changes

2022-01-30 18:56 UTC, ureeves commented on rusk-wallet/src/lib/clients.rs
> +
Could we also deserialize the transaction and print its hash here?

2022-01-30 18:56 UTC, ureeves commented on rusk-wallet/src/lib/clients.rs
> +
As base58 that is

2022-01-30 18:58 UTC, ureeves commented on rusk-wallet/Cargo.toml
> +dusk-wallet-core = "0.8.0-rc.1"
If you're serializing transactions this should now be `to_var_bytes` instead of `to_bytes`

2022-01-31 09:07 UTC, ureeves requested changes
Please remove the `.DS_STORE` file

2022-01-31 09:27 UTC, ureeves approved these changes

2022-01-31 09:37 UTC, ureeves approved these changes

2022-01-31 10:12 UTC, merged