consensus: add merkle-tree implementation
dusk-network/rusk pull request #903
Opened 2023-05-26 08:39 UTC by herr-seppia

- Add `dusk-merkle` dependency
- Add `fn consensus::merkle::merkle_root` wrapping `dusk-merkle` to guarantee compatibility with dusk-blockchain's merkle-tree

See also #847

2023-05-26 10:42 UTC, moCello reviewed
There might be a nicer way to get a 'smaller' merkle tree without needing to create one for each height and batch inserting leaves into it.

If you create a tree, insert leaves and get an opening, you can traverse the opening to the first node that has more than one children different from the `EMPTY_SUBTREES` of the height. The first note that has more than one children set is the root of the smallest tree that can hold all the leaves that have been inserted. If at each level there is only one child, the tree only holds one leaf and the parent of that leaf is the smallest root

2023-05-26 13:49 UTC, herr-seppia commented
@moCello you're right

Pushed the implementation you suggested.
Feel free to have a look, in the meanwhile I want to sketch an additional approach

2023-05-26 14:46 UTC, moCello requested changes
Some change requests, see comments

2023-05-26 14:46 UTC, moCello commented on consensus/src/merkle.rs
> +            (self.tree.len() as f64 - 1f64).sqrt().floor() as usize + 1;
sqrt works only with ARITY=2 which is no problem in this case but not so nice for a general approach

2023-05-26 14:46 UTC, moCello commented on consensus/src/merkle.rs
> +            .opening(0)
We insert leaves at a specific position so there could be a case where there is no leaf at pos=0 but the tree is still not empty. Use the walker to retrieve any leaf instead

2023-05-26 14:46 UTC, moCello commented on consensus/src/merkle.rs
> +        opening.branch()[H - inner_tree_height - 1][0].0
This also assumes that the leaves are all inserted in order, but the tree is sparse. I'm afraid you will need to traverse the branch to check for the first node that holds more than one children.

2023-05-26 14:52 UTC, moCello approved these changes
Previous comments only apply to a general approach but in this special case it is actually not needed.
So LGTM

2023-05-29 09:28 UTC, goshawk-3 approved these changes

2023-05-29 09:38 UTC, merged